
test_src += files(
    'c_types.cpp',
    'c_types.hpp',
    'compat.cpp',
    'compat.hpp',
    'cpp_types.cpp',
    'cpp_types.hpp',
    'fuse_impl.c',
    'fuse_impl.h',
    'fuse_impl_run.c',
    'fuse_impl_run.h',
    'generic.cpp',
    'generic.hpp',
    'helpers.hpp',
    'json.cpp',
    'json.hpp',
    'json_schema.cpp',
    'json_schema.hpp',
    'main.cpp',
    'mock_file.cpp',
    'mock_file.hpp',
    'string_maker.hpp',
    'support.hpp',
)
